const fs=require('fs'),assert=require('assert'),crypto=require('crypto');
const loader=fs.readFileSync('tests/hand_rules_v10.cjs','utf8').split('let sims=')[0].replaceAll('prototypes/kasumigaseki_cards_v10.html','prototypes/kasumigaseki_cards_v17.html').replace('(after.hand-before.hand+1)*1.8','(Math.min(after.hand,7)-Math.min(before.hand-1,7))*1.8').replace('score+=(battle.boost-base.boost)*0.9;','score+=(battle.boost-base.boost)*0.9+(battle.nextDraw-base.nextDraw)*0.9;');const r=new Function('require',loader+';return load;')(require)('native');
r(`function pairTrial(deck,affs,profile,prep,s){start('admin');state.deck=deck.slice();state.owned={};for(let c of Object.values(C))if(!c.bad&&affs.includes(c.aff))state.owned[c.id]=2;state.clears=0;state.tokens=0;state.difficulty=profile==='intro'?'normal':'advanced';state.challenge=profile;seed=s>>>0;choosePrep(prep);let pm=fightMeasured('tactical',true),prepWin=!!state.soft;begin('final');let fm=fightMeasured('tactical',true);return {win:state.phase==='reward',prepWin,timeouts:+pm.timedOut + +fm.timedOut};}`);
const standardPairs={"admin+politics":'admin',"press+community":'regional',"politics+noir":'noir',"admin+business":'economic'};
const attrs=['admin','politics','press','business','community','noir'],profiles=['intro','finance','public'],preps=['policy','media','party'],catalog=r('Object.values(C).filter(c=>!c.bad)'),training=Number(process.env.TRAIN||20),trials=Number(process.env.TRIALS||100),count=Number(process.env.CANDIDATES||12),rows=[],search=[];let rng=159753;function rand(n){rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng%n;}
function legal(d,affs){return d.length===20&&d.every(id=>d.filter(x=>x===id).length<=2)&&affs.every(aff=>d.filter(id=>catalog.find(c=>c.id===id).aff===aff).length>=6&&d.some(id=>catalog.find(c=>c.id===id).aff===aff&&catalog.find(c=>c.id===id).type==='person'))&&d.filter(id=>catalog.find(c=>c.id===id).type==='attack').length>=4;}
function measure(deck,affs,profile,prep,n,base){let row={pair:affs.join('+'),affs,profile,prep,total:n,wins:0,prepWins:0,timeouts:0,outcomes:''};for(let i=0;i<n;i++){let x=r(`pairTrial(${JSON.stringify(deck)},${JSON.stringify(affs)},'${profile}','${prep}',${base+i*7919})`);row.wins+=x.win;row.prepWins+=x.prepWin;row.timeouts+=x.timeouts;row.outcomes+=+x.win;}row.rate=100*row.wins/n;assert(row.timeouts===0);return row;}
for(let a=0;a<attrs.length;a++)for(let b=a+1;b<attrs.length;b++){let affs=[attrs[a],attrs[b]],pool=catalog.filter(c=>affs.includes(c.aff)),initial=affs.flatMap(aff=>{let cards=pool.filter(c=>c.aff===aff),person=cards.find(c=>c.type==='person').id,ordinary=cards.filter(c=>c.type!=='person').sort((a,b)=>({attack:0,defense:1,prep:2,disrupt:3}[a.type]-{attack:0,defense:1,prep:2,disrupt:3}[b.type])||a.cost-b.cost),ids=[person];for(let c of ordinary)for(let i=0;i<2&&ids.length<10;i++)ids.push(c.id);return ids;}),decks=[initial];assert(legal(initial,affs));
for(let k=1;k<count;k++){let d=initial.slice();for(let j=0;j<12;j++){let next=d.slice();next[rand(20)]=pool[rand(pool.length)].id;if(legal(next,affs))d=next;}decks.push(d);}
if(standardPairs[affs.join('+')])decks[1]=r(`BASEDECKS.${standardPairs[affs.join('+')]}.slice()`);if(process.env.PAIRS&&!process.env.PAIRS.split(',').includes(affs.join('+')))continue;
let scores=decks.map((deck,index)=>({index,wins:['finance','public'].flatMap(profile=>preps.map(prep=>measure(deck,affs,profile,prep,training,135790))).reduce((s,x)=>s+x.wins,0),total:training*6})).sort((a,b)=>b.wins-a.wins||a.index-b.index),selected=decks[scores[0].index];search.push({affs,pool:pool.map(c=>c.id),scores,deck:selected});for(let profile of profiles)for(let prep of preps){let row=measure(selected,affs,profile,prep,trials,864209);rows.push(row);console.log(row.pair,profile,prep,row.rate);}}
if(process.env.PAIRS){const old=JSON.parse(fs.readFileSync('reports/attribute_pairs_v17.json','utf8'));const selected=process.env.PAIRS.split(',');rows.unshift(...old.rows.filter(x=>!selected.includes(x.pair)));search.unshift(...old.search.filter(x=>!selected.includes(x.affs.join('+'))));}
fs.writeFileSync('reports/attribute_pairs_v17.json',JSON.stringify({sourceSha256:crypto.createHash('sha256').update(fs.readFileSync('prototypes/kasumigaseki_cards_v17.html')).digest('hex'),training,trials,candidates:count,method:'All 15 two-attribute pairs. Full holdings of both attributes (2 each), not initial assets or first reward. Same number of candidates (the known starter replaces one candidate for the four standard pairs); minimum6 cards and one person per attribute, minimum4 attacks, legal20/max2. Choose on separate training seeds, averaged across finance/public and all preparations. Validate unchanged selected deck over intro/finance/public and all preparations, tactical policy only; no prep-specific build, no human/browser test, no optimality guarantee. Rewards occur after each trial and do not carry into the next.',catalog,search,rows},null,2));assert(rows.every(x=>x.timeouts===0));
