const fs=require('fs'),assert=require('assert'),crypto=require('crypto');
const version=process.env.VERSION||'v17';assert(version==='v17');
const loader=fs.readFileSync('tests/hand_rules_v10.cjs','utf8').split('let sims=')[0].replaceAll('prototypes/kasumigaseki_cards_v10.html','prototypes/kasumigaseki_cards_'+version+'.html').replace('(after.hand-before.hand+1)*1.8','(Math.min(after.hand,7)-Math.min(before.hand-1,7))*1.8').replace('score+=(battle.boost-base.boost)*0.9;','score+=(battle.boost-base.boost)*0.9+(battle.nextDraw-base.nextDraw)*0.9;');
const seedOffset=Number(process.env.SEED_OFFSET||0);
const r=new Function('require',loader+';return load;')(require)('native'),types=['admin','regional','noir','economic'],preps=['policy','media','party'];
r(`function firstStage(type,i,base){start(type);state.clears=0;state.tokens=0;state.difficulty='normal';state.challenge='intro';seed=(base+i*7919)>>>0;const initialOwned=copy(state.owned);choosePrep(['policy','media','party'][i%3]);let pm=fightMeasured('simple',true);begin('final');let fm=fightMeasured('simple',true);return {win:state.phase==='reward',snapshot:copy(state),initialOwned,timeout:+pm.timedOut + +fm.timedOut};}
function legalTemplate(target,owned,starter){let deck=[];for(let id of target)if(deck.filter(x=>x===id).length<Math.min(2,owned[id]||0))deck.push(id);for(let id of starter)if(deck.length<20&&deck.filter(x=>x===id).length<Math.min(2,owned[id]||0))deck.push(id);if(deck.length!==20)throw Error('template cannot fill');if(deck.every(id=>deck.filter(x=>x===id).length===starter.filter(x=>x===id).length))return starter.slice();return deck;}
function secondStage(first,target,mode,prep,policy,s){state=copy(first.snapshot);battle=null;history=[];pending=null;let starter=state.deck.slice();let choice=null;if(state.pickPending)throw Error('choice failed');continueEpilogue();advanceStage();if(state.phase!=='case'||caseProfile()!==CASE_PROFILES.finance)throw Error('advance failed');let available=mode==='rewards'?state.owned:first.initialOwned;state.deck=mode==='unchanged'?starter:legalTemplate(target,available,starter);if(state.deck.some(id=>state.deck.filter(x=>x===id).length>Math.min(2,state.owned[id]||0)))throw Error('unowned');let built=state.deck.slice();seed=s>>>0;choosePrep(prep);let pm=fightMeasured(policy,true),prepWin=!!state.soft;begin('final');let fm=fightMeasured(policy,true);return {win:state.phase==='reward',prepWin,timeouts:+pm.timedOut + +fm.timedOut,deck:built,choice,added:built.filter(id=>!starter.includes(id))};}`);
if(process.env.PRESSURE)r(`CASE_PROFILES.finance.pressure=${Number(process.env.PRESSURE)}`);
if(process.env.BROAD_SCRUTINY)r(`const nativeDeck=enemyDeck;enemyDeck=function(kind){let deck=nativeDeck(kind);if(kind==='final'&&caseProfile()===CASE_PROFILES.finance)for(let c of deck){let e=c.effects.find(e=>e.op==='suppress');if(e){delete e.aff;c.name='参考人聴取';}}return deck;};`);
const prev=JSON.parse(fs.readFileSync('reports/collection_v14.json','utf8')),training=Number(process.env.TRAIN||60),trials=Number(process.env.TRIALS||300),rows=[],selection=[],firstRows=[],frozen=process.env.SELECTION_PATH?JSON.parse(fs.readFileSync(process.env.SELECTION_PATH,'utf8')).selection:null;
const manual={admin:[['planExplain','whip'],['staffChange','investigate']],regional:[['petition','whip'],['investigate','voice']],noir:[['favor','whip'],['silence','investigate']],economic:[['clean','whip'],['clean','budgetReview']]};
for(let type of types){let starter=r(`BASEDECKS.${type}.slice()`),edit=starter.slice();for(let [from,to]of manual[type]){let k=edit.indexOf(from);if(k>=0&&edit.filter(x=>x===to).length<2)edit[k]=to;}let candidates=[starter,...prev.search.filter(x=>x.type===type).map(x=>x.deck),edit];let trained=frozen?[]:Array.from({length:training},(_,i)=>r(`firstStage('${type}',${i},112233)`)).filter(x=>x.win);let scores=candidates.map((deck,index)=>{let wins=0,timeout=0;for(let i=0;i<trained.length;i++)for(let prep of preps){let x=r(`secondStage(${JSON.stringify(trained[i])},${JSON.stringify(deck)},'rewards','${prep}','tactical',${334455+i*7919})`);wins+=x.win;timeout+=x.timeouts;}return {index,wins,total:trained.length*3,timeout};}).sort((a,b)=>b.wins-a.wins||a.index-b.index);assert(scores.every(x=>x.timeout===0));let target=frozen?frozen.find(x=>x.type===type).target:candidates[scores[0].index];selection.push({type,scores,target});let samples=Array.from({length:trials},(_,i)=>r(`firstStage('${type}',${i},${667788+seedOffset})`)),passed=samples.map((x,i)=>({...x,i})).filter(x=>x.win);firstRows.push({type,total:trials,wins:passed.length,timeouts:samples.reduce((s,x)=>s+x.timeout,0),rate:100*passed.length/trials,duplicateTokens:passed.map(x=>x.snapshot.tokens),randomNewCounts:passed.map(x=>Object.keys(x.snapshot.owned).filter(id=>!x.initialOwned[id]).length)});
for(let prep of preps)for(let policy of (process.env.POLICIES||'simple,tactical').split(','))for(let mode of (process.env.MODES||'unchanged,owned,rewards').split(',')){let row={type,prep,policy,mode,total:passed.length,wins:0,prepWins:0,timeouts:0,outcomes:'',choices:{},decks:{}};for(let first of passed){let x=r(`secondStage(${JSON.stringify(first)},${JSON.stringify(target)},'${mode}','${prep}','${policy}',${990011+seedOffset+first.i*7919})`);row.wins+=x.win;row.prepWins+=x.prepWin;row.timeouts+=x.timeouts;row.outcomes+=+x.win;row.choices[x.choice]=(row.choices[x.choice]||0)+1;let key=x.deck.join(',');row.decks[key]=(row.decks[key]||0)+1;}row.rate=100*row.wins/row.total;rows.push(row);console.log(type,prep,policy,mode,row.rate.toFixed(1));}}
const source=fs.readFileSync('prototypes/kasumigaseki_cards_'+version+'.html');fs.writeFileSync(process.env.REPORT_PATH||'reports/campaign_v17.json',JSON.stringify({sourceSha256:crypto.createHash('sha256').update(source).digest('hex'),version,training,trials,seedOffset,fixedSelectionSource:process.env.SELECTION_PATH||null,pressureOverride:process.env.PRESSURE?Number(process.env.PRESSURE):null,broadScrutinyOverride:!!process.env.BROAD_SCRUTINY,method:'First stage simple bot, prep cycles equally; actual native random5 reward and duplicate tokens. Normal mode only, initial ownership equals selected20 cards. Five native independent random rewards, no chosen reward. No exchanges, even when duplicate tokens allow one. Four templates per starter chosen on disjoint training seeds by stage2 tactical averaged over3 preparations. No holdout-dependent build search. Stage2 conditional on first-stage success; same sampled rewards and seeds across modes. Unchanged=starter; owned=template adapted to original holdings; rewards=template adapted to earned holdings. Missing copies replaced with legal starter cards. Full prep+final both stages, no human/browser test. Same second-stage deck during preparation/final.',selection,firstRows,rows},null,2));assert(firstRows.every(x=>x.timeouts===0)&&rows.every(x=>x.timeouts===0));
