const fs=require('fs'),vm=require('vm'),assert=require('assert');let storage={},els={};let src=fs.readFileSync('prototypes/kasumigaseki_cards_v06.html','utf8').split('<script>')[1].split('</script>')[0];function context(){return vm.createContext({console,Math,JSON,Object,Array,document:{getElementById:id=>els[id]||={innerHTML:'',showModal(){},close(){}}},localStorage:{getItem:k=>storage[k],setItem:(k,v)=>storage[k]=v},confirm:()=>true})}let ctx=context();vm.runInContext(src,ctx);const r=s=>vm.runInContext(s,ctx);
r("start('admin');choosePrep('policy')");assert.equal(r('battle.kind'),'prep');
r("battle.hand=['delay'];battle.energy=3;let before=JSON.stringify(battle);play(0);target(pending.targets[0]);if(!battle.deferred.length)throw Error('no deferred');undo();if(JSON.stringify(battle)!==before)throw Error('undo mismatch')");
r("play(0);target(pending.targets[0]);end();if(battle.plan.reduce((n,p)=>n+p.cost,0)>3)throw Error('cost overflow')");
r("finish(true)");assert.equal(r('state.soft'),'finance');r("begin('final')");assert(r("battle.enemyPile.concat(battle.enemyHand).filter(c=>c.issue==='finance').every(c=>c.name==='財源説明済み')"));
r("battle.hand=['deal'];battle.energy=3;play(0);target(pending.targets[0]);if(!battle.enemyPile.some(c=>c.issue==='scandal'))throw Error('scandal missing');undo();if(battle.enemyPile.some(c=>c.issue==='scandal'))throw Error('scandal undo')");
r("battle.plan=[{uid:91,name:'更迭',cost:1,target:'leader',effects:[{op:'bounce'}]}];battle.allies=[{id:'leader',disabledUntil:0}];battle.hand=[];end();if(!battle.hand.includes('leader')||battle.allies.length)throw Error('bounce return')");
r("battle.hand=['invest'];battle.energy=3;play(0);battle.plan=[];end();if(battle.energy!==4||battle.hand.length!==7)throw Error('investment')");
r("battle.hand=['report'];battle.enemyHP=1;battle.enemyBlock=0;battle.energy=3;play(0);if(battle.outcome!=='win')throw Error('pending victory');undo();if(battle.enemyHP!==1)throw Error('win undo');play(0);end();if(state.phase!=='reward')throw Error('reward');state.phase='epilogue';render();save()");ctx=context();vm.runInContext(src,ctx);assert.equal(r('state.phase'),'epilogue');assert.equal(r('state.deck.length'),20);
for(let type of ['admin','regional','noir','economic']){r(`start('${type}')`);assert.equal(r('state.deck.length'),20);assert(r('state.deck.every(id=>state.deck.filter(x=>x===id).length<=2)'));}
for(let phase of ['intro','case','prepared','reward','epilogue','defeat','deck']){r(`state.phase='${phase}';state.reward=[];render()`);for(let m of els.app.innerHTML.matchAll(/onclick="([^"]*)"/g))new Function(m[1]);}r("state.phase='case';choosePrep('policy')");for(let m of els.app.innerHTML.matchAll(/onclick="([^"]*)"/g))new Function(m[1]);
console.log('PASS: deck limits, targeted undo, delayed action budget, issue replacement, scandal/undo, person return, investment, victory confirm, save reload, UI handler syntax.');
