const fs=require('fs'),vm=require('vm'),assert=require('assert');let storage={},els={};let src=fs.readFileSync('prototypes/kasumigaseki_cards_v13.html','utf8').split('<script>')[1].split('</script>')[0];function context(){return vm.createContext({console,Math,JSON,Object,Array,document:{getElementById:id=>els[id]||={innerHTML:'',showModal(){},close(){}}},localStorage:{getItem:k=>storage[k],setItem:(k,v)=>storage[k]=v},confirm:()=>true})}let ctx=context();vm.runInContext(src,ctx);const r=s=>vm.runInContext(s,ctx);
r("start('admin');choosePrep('policy')");assert.equal(r('battle.kind'),'prep');
r("battle.hand=['delay'];battle.energy=3;let before=JSON.stringify(battle);play(0);target(pending.targets[0]);if(!battle.deferred.length)throw Error('no deferred');undo();if(JSON.stringify(battle)!==before)throw Error('undo mismatch')");
r("play(0);target(pending.targets[0]);end();if(battle.plan.reduce((n,p)=>n+p.cost,0)>3)throw Error('cost overflow')");
r("finish(true)");assert.equal(r('state.soft'),'finance');r("begin('final')");assert(r("battle.enemyPile.concat(battle.enemyHand).filter(c=>c.issue==='finance').every(c=>c.name==='財源説明済み')"));
r("battle.hand=['deal'];battle.energy=3;play(0);target(pending.targets[0]);if(!battle.enemyPile.some(c=>c.issue==='scandal'))throw Error('scandal missing');undo();if(battle.enemyPile.some(c=>c.issue==='scandal'))throw Error('scandal undo')");
r("battle.plan=[{uid:91,name:'更迭',cost:1,target:'leader',effects:[{op:'bounce'}]}];battle.allies=[{id:'leader',disabledUntil:0}];battle.hand=[];end();if(!battle.hand.includes('leader')||battle.allies.length)throw Error('bounce return')");
r("battle.hand=['invest'];battle.energy=3;play(0);battle.plan=[];end();if(battle.energy!==4||battle.hand.length!==2)throw Error('investment')");
r("battle.hand=['report'];battle.enemyHP=1;battle.enemyBlock=0;battle.energy=3;play(0);if(battle.outcome!=='win')throw Error('pending victory');undo();if(battle.enemyHP!==1)throw Error('win undo');play(0);end();if(state.phase!=='reward')throw Error('reward');state.phase='epilogue';render();save()");ctx=context();vm.runInContext(src,ctx);assert.equal(r('state.phase'),'epilogue');assert.equal(r('state.deck.length'),20);
for(let type of ['admin','regional','noir','economic']){r(`start('${type}')`);assert.equal(r('state.deck.length'),20);assert(r('state.deck.every(id=>state.deck.filter(x=>x===id).length<=2)'));}
r("start('admin');choosePrep('policy');battle.allies=[{id:'official',disabledUntil:0}];battle.growth={official:{progress:0,level:0}};battle.hand=['answer'];battle.energy=3;play(0);if(battle.growth.official.progress!==1)throw Error('growth first');battle.plan=[];end();if(battle.growth.official.progress!==1)throw Error('growth reset');battle.hand=['answer'];play(0);if(battle.growth.official.level!==1)throw Error('growth missing');undo();if(battle.growth.official.level!==0||battle.growth.official.progress!==1)throw Error('growth undo');play(0);battle.hand=['procedure'];battle.energy=3;battle.enemyBlock=0;battle.enemyHP=100;play(0);if(battle.enemyHP!==85)throw Error('grown cost2 bonus');battle.allies[0].disabledUntil=battle.turn+1;battle.hand=['procedure'];battle.energy=3;battle.enemyHP=100;play(0);if(battle.enemyHP!==89)throw Error('suppressed growth still fired');save()");ctx=context();vm.runInContext(src,ctx);assert.equal(r('battle.growth.official.level'),1);
r("begin('final');if(battle.growth&&Object.keys(battle.growth).length)throw Error('growth carried to next battle')");
r("start('admin');choosePrep('policy');if(battle.maxEnemy!==30||battle.hp!==30)throw Error('HP30');battle.allies=[{id:'official',disabledUntil:0}];battle.growth={official:{progress:2,level:1}};battle.nextBlock=0;battle.plan=[];end();if(battle.block!==5)throw Error('grown start block');battle.allies[0].disabledUntil=battle.turn+1;battle.plan=[];end();if(battle.block!==0)throw Error('disabled start block');battle.enemyPile=Array.from({length:8},()=>makeEnemyCard('parliament',false,0));battle.deferred=[];battle.enemyHand=[];planTurn();if(battle.plan.find(p=>p.effects.some(e=>e.op==='bounce')).target!=='official')throw Error('bounce target');render();if(!document.getElementById('app').innerHTML.includes('issuebadge'))throw Error('issue label');if(!cardHTML(C.answer).includes('コスト 1'))throw Error('visible cost');battle.plan=[makeEnemyCard('finance')];if(can('whip'))throw Error('no-target whip enabled')");
for(let [type,affs] of Object.entries({admin:['admin','politics'],regional:['community','press'],noir:['noir','politics'],economic:['business','admin']})){r(`start('${type}')`);assert(r(`state.deck.every(id=>${JSON.stringify(affs)}.includes(C[id].aff))`));}
r("start('admin');choosePrep('policy');battle.hand=['answer'];battle.block=0;battle.plan=[{uid:111,issue:'finance',cost:1,effects:[{op:'damage',n:10}],cancelled:false}];let previewState=JSON.stringify({battle,seed,history});let prediction=previewFor('answer');if(prediction.net!==3)throw Error('preview defense');if(JSON.stringify({battle,seed,history})!==previewState)throw Error('preview mutated state');preview(0);if(!document.getElementById('help').innerHTML.includes('10 → 3'))throw Error('preview text');play(0);if(Math.max(0,forecast()-battle.block)!==prediction.net)throw Error('preview mismatch');undo();battle.hand=['delay'];let delayed=previewFor('delay',111);if(delayed.net!==0)throw Error('target preview');document.getElementById('reviewDifficulty').value='ちょうどよい';document.getElementById('reviewConfusing').value='<script>';document.getElementById('reviewChoice').value='財源';document.getElementById('reviewLearning').value='防御';saveFeedback();if(!document.getElementById('help').innerHTML.includes('&lt;script&gt;'))throw Error('feedback escape');if(state.feedback.length!==1)throw Error('feedback persistence');");
for(let phase of ['intro','case','prepared','reward','epilogue','defeat','deck']){r(`state.phase='${phase}';state.reward=[];render()`);for(let m of els.app.innerHTML.matchAll(/onclick="([^"]*)"/g))new Function(m[1]);}r("state.phase='case';choosePrep('policy')");for(let m of els.app.innerHTML.matchAll(/onclick="([^"]*)"/g))new Function(m[1]);
console.log('PASS: deck limits, targeted undo, delayed action budget, issue replacement, scandal/undo, person return, investment, victory confirm, save reload, UI handler syntax.');
r("start('admin');choosePrep('policy');if(battle.hand.length!==5)throw Error('initial5');battle.hand=['answer','procedure'];battle.pile=['delay'];battle.plan=[];end();if(JSON.stringify(battle.hand)!==JSON.stringify(['answer','procedure','delay']))throw Error('retain plus one');battle.hand=Array(8).fill('answer');let overflowBefore=JSON.stringify(battle);let overflowTurn=battle.turn;end();if(battle.turn!==overflowTurn||can('answer'))throw Error('overflow allowed action');discardOverflow(0);if(battle.hand.length!==7)throw Error('overflow discard');undo();if(JSON.stringify(battle)!==overflowBefore)throw Error('overflow undo');battle.hand=['investigate'];battle.pile=['answer','procedure'];battle.energy=3;play(0);if(battle.hand.length!==2||battle.energy!==2)throw Error('extra draw2');");
r("start('admin');choosePrep('policy');battle.enemyHand=[{id:'held',name:'保留',cost:2,effects:[{op:'damage',n:1}]},{id:'used',name:'消費',cost:1,effects:[{op:'damage',n:1}]}];battle.plan=[{...battle.enemyHand[1],cancelled:true}];battle.enemyPile=[{id:'new',name:'新規',cost:1,effects:[{op:'damage',n:1}]}];battle.enemyDiscard=[];end();if(!battle.enemyHand.some(x=>x.id==='held')||!battle.enemyHand.some(x=>x.id==='new')||battle.enemyHand.some(x=>x.id==='used')||!battle.enemyDiscard.some(x=>x.id==='used'))throw Error('enemy retain canceled consumption');battle.enemyHand=Array.from({length:10},(_,i)=>({id:'e'+i,cost:1,effects:[{op:'damage',n:i+1}]}));planTurn();if(battle.enemyHand.length>7||battle.plan.reduce((n,p)=>n+p.cost,0)>3)throw Error('enemy cap/budget');");
for(let type of ['admin','regional','noir','economic']){r(`start('${type}')`);assert(r('state.deck.filter(id=>C[id].type==="person").length===2'));assert(r('state.deck.some(id=>C[id].cost===2)'));}
r("state.feedback=[{difficulty:'保存'}];newGame();if(state.phase!=='intro'||state.deck.length||state.feedback.length!==1)throw Error('fresh deck reset');if(!localStorage.getItem('seikyoku-v13'))throw Error('version save key');");
console.log('PASS: retained initial5/draw1, explicit overflow/undo, draw2, canceled enemy consumption, enemy cap7/cost3, distinct people, fresh start, v13 save isolation.');
r("start('regional');choosePrep('media');battle.allies=[{id:'reporter',disabledUntil:0}];battle.growth={reporter:{progress:3,level:1}};battle.used={};battle.hand=['brief'];battle.pile=['answer','answer','answer'];battle.energy=3;play(0);if(battle.hand.length!==1||battle.used.grown_reporter)throw Error('reporter defense extra draw');battle.hand=['report'];battle.energy=3;battle.enemyHP=30;play(0);if(!battle.used.grown_reporter||battle.hand.length!==1)throw Error('reporter attack draw');if(Object.values(C).some(c=>c.text.includes('攻撃は＋6')))throw Error('stale growth text');");
console.log('PASS: reporter grown draw only on attack, growth description matches +4.');
r("start('admin');choosePrep('policy');battle.hand=['delay'];battle.enemyHand=[{id:'reserved',name:'予約',cost:1,effects:[{op:'damage',n:1}]}];battle.plan=[{...battle.enemyHand[0],uid:99,cancelled:false}];battle.enemyPile=Array.from({length:4},()=>({id:'new',name:'新規',cost:2,effects:[{op:'damage',n:1}]}));battle.enemyDiscard=[];battle.energy=3;play(0);target(99);end();if(battle.enemyDiscard.filter(x=>x.id==='reserved').length!==1||!battle.plan.some(x=>x.id==='reserved'&&x.delayed))throw Error('delay not consumed/reserved');end();if(battle.enemyDiscard.filter(x=>x.id==='reserved').length!==1)throw Error('delay consumed twice');");
console.log('PASS: postponed action consumes card once and fits following turn budget.');
r("start('admin');choosePrep('policy');battle.turn=2;battle.enemyHand=[makeEnemyCard('parliament',false,0),makeEnemyCard('finance',false,1)];battle.enemyPile=[makeEnemyCard('region',false,1)];battle.allies=[{id:'leader',disabledUntil:0},{id:'official',disabledUntil:0}];battle.growth={official:{level:1,progress:2}};battle.deferred=[];let clean=JSON.stringify(battle);battle.hand=['answer'];battle.pile=['procedure'];planTurn();let publicPlan=JSON.stringify(battle.plan);battle=JSON.parse(clean);battle.hand=['force','investigate','report'];battle.pile=['deal','silence'];planTurn();if(JSON.stringify(battle.plan)!==publicPlan)throw Error('enemy peeks at player cards');let savedTarget=battle.plan.find(p=>p.effects.some(e=>e.op==='bounce'))?.target;if(savedTarget!=='official')throw Error('growth priority target');battle.allies.push({id:'reporter',disabledUntil:0});render();if(battle.plan.find(p=>p.effects.some(e=>e.op==='bounce')).target!==savedTarget)throw Error('preview target changed');");
console.log('PASS: changing hidden player hand/pile leaves plan unchanged; grown person prioritized; forecast targets fixed after placement.');
r("newGame();start('admin');state.phase='case';selectProfile('finance');if(caseProfile()!==CASE_PROFILES.intro)throw Error('locked finance');state.clears=1;selectProfile('finance');if(caseProfile()!==CASE_PROFILES.finance)throw Error('finance unlock');state.prep='policy';state.soft='finance';let deck=enemyDeck('final');if(deck.length!==18||deck.filter(c=>c.issue==='finance').length!==6||deck.filter(c=>c.issue==='finance').some(c=>!c.name.includes('説明済み')))throw Error('finance composition');selectProfile('public');if(caseProfile()!==CASE_PROFILES.finance)throw Error('locked public');state.clears=2;selectProfile('public');deck=enemyDeck('final');if(deck.filter(c=>c.issue==='region').length!==6||deck.filter(c=>c.issue==='press').length!==6)throw Error('public composition');selectProfile('intro');if(caseProfile()!==CASE_PROFILES.intro)throw Error('return to intro');state.prep='policy';begin('final');battle.outcome='win';end();if(!state.pickPending||state.reward.length!==2)throw Error('reward 2 random');home();if(state.phase!=='reward')throw Error('reward bypass');continueEpilogue();if(state.phase!=='reward')throw Error('unselected reward skip');state.owned.investigate=0;pickReward('investigate');if(state.owned.investigate!==1||state.pickPending)throw Error('selected reward');pickReward('investigate');if(state.owned.investigate!==1)throw Error('reward double');continueEpilogue();if(state.phase!=='epilogue')throw Error('epilogue after reward');state.phase='reward';state.pickPending=true;for(let c of Object.values(C))if(!c.bad)state.owned[c.id]=2;pickReward('token');if(state.pickPending)throw Error('full collection fallback');");
r("newGame();start('admin');choosePrep('policy');if(!battleHTML().includes('入門ヒント'))throw Error('tutorial tip');state.difficulty='advanced';state.challenge='finance';if(battleHTML().includes('入門ヒント'))throw Error('hint in advanced');state.phase='case';render();for(let m of document.getElementById('app').innerHTML.matchAll(/onclick=\"([^\"]*)\"/g))new Function(m[1]);state.phase='reward';state.pickPending=true;state.reward=[];render();for(let m of document.getElementById('app').innerHTML.matchAll(/onclick=\"([^\"]*)\"/g))new Function(m[1]);");
console.log('PASS: progressive profiles/unlocks, equal HP/deck size, issue-count softening, chosen reward/gating/no double claim/full collection, tips and new UI handler syntax.');
r("state.phase='case';state.clears=2;selectProfile('public');state.prep='policy';let cards=enemyDeck('prep');let first=cards.find(c=>c.issue==='finance'&&c.cost===2);if(first.effects[0].n!==ISSUES.finance.damage)throw Error('prep difficulty changed');let finalCards=enemyDeck('final');state.soft=null;finalCards=enemyDeck('final');let finalFinance=finalCards.find(c=>c.issue==='finance'&&c.cost===2);if(finalFinance.effects[0].n!==ISSUES.finance.damage+2)throw Error('public attack bonus');state.soft='press';state.phase='prepared';render();if(!document.getElementById('app').innerHTML.includes('強いカード6枚'))throw Error('softened count UI');");
console.log('PASS: common preparation damage, +2 late final, six-card preparation-result label.');
r("let light=enemyDeck('final').find(c=>c.issue==='finance'&&c.cost===1);if(light.effects[0].n!==Math.max(2,ISSUES.finance.damage-3)+1)throw Error('light attack overboosted');");
console.log('PASS: later pressure increases strong cost2 actions only, leaves cost1 at +1.');
