const fs=require('fs'),vm=require('vm'),assert=require('assert');let storage={},els={};let src=fs.readFileSync('prototypes/kasumigaseki_cards_v09.html','utf8').split('<script>')[1].split('</script>')[0];function context(){return vm.createContext({console,Math,JSON,Object,Array,document:{getElementById:id=>els[id]||={innerHTML:'',showModal(){},close(){}}},localStorage:{getItem:k=>storage[k],setItem:(k,v)=>storage[k]=v},confirm:()=>true})}let ctx=context();vm.runInContext(src,ctx);const r=s=>vm.runInContext(s,ctx);
r("start('admin');choosePrep('policy')");assert.equal(r('battle.kind'),'prep');
r("battle.hand=['delay'];battle.energy=3;let before=JSON.stringify(battle);play(0);target(pending.targets[0]);if(!battle.deferred.length)throw Error('no deferred');undo();if(JSON.stringify(battle)!==before)throw Error('undo mismatch')");
r("play(0);target(pending.targets[0]);end();if(battle.plan.reduce((n,p)=>n+p.cost,0)>3)throw Error('cost overflow')");
r("finish(true)");assert.equal(r('state.soft'),'finance');r("begin('final')");assert(r("battle.enemyPile.concat(battle.enemyHand).filter(c=>c.issue==='finance').every(c=>c.name==='財源説明済み')"));
r("battle.hand=['deal'];battle.energy=3;play(0);target(pending.targets[0]);if(!battle.enemyPile.some(c=>c.issue==='scandal'))throw Error('scandal missing');undo();if(battle.enemyPile.some(c=>c.issue==='scandal'))throw Error('scandal undo')");
r("battle.plan=[{uid:91,name:'更迭',cost:1,target:'leader',effects:[{op:'bounce'}]}];battle.allies=[{id:'leader',disabledUntil:0}];battle.hand=[];end();if(!battle.hand.includes('leader')||battle.allies.length)throw Error('bounce return')");
r("battle.hand=['invest'];battle.energy=3;play(0);battle.plan=[];end();if(battle.energy!==4||battle.hand.length!==6)throw Error('investment')");
r("battle.hand=['report'];battle.enemyHP=1;battle.enemyBlock=0;battle.energy=3;play(0);if(battle.outcome!=='win')throw Error('pending victory');undo();if(battle.enemyHP!==1)throw Error('win undo');play(0);end();if(state.phase!=='reward')throw Error('reward');state.phase='epilogue';render();save()");ctx=context();vm.runInContext(src,ctx);assert.equal(r('state.phase'),'epilogue');assert.equal(r('state.deck.length'),20);
for(let type of ['admin','regional','noir','economic']){r(`start('${type}')`);assert.equal(r('state.deck.length'),20);assert(r('state.deck.every(id=>state.deck.filter(x=>x===id).length<=2)'));}
r("start('admin');choosePrep('policy');battle.allies=[{id:'official',disabledUntil:0}];battle.growth={official:{progress:0,level:0}};battle.hand=['answer'];battle.energy=3;play(0);if(battle.growth.official.progress!==1)throw Error('growth first');battle.plan=[];end();if(battle.growth.official.progress!==1)throw Error('growth reset');battle.hand=['answer'];play(0);if(battle.growth.official.level!==1)throw Error('growth missing');undo();if(battle.growth.official.level!==0||battle.growth.official.progress!==1)throw Error('growth undo');play(0);battle.hand=['procedure'];battle.energy=3;battle.enemyBlock=0;battle.enemyHP=100;play(0);if(battle.enemyHP!==87)throw Error('grown cost2 bonus');battle.allies[0].disabledUntil=battle.turn+1;battle.hand=['procedure'];battle.energy=3;battle.enemyHP=100;play(0);if(battle.enemyHP!==91)throw Error('suppressed growth still fired');save()");ctx=context();vm.runInContext(src,ctx);assert.equal(r('battle.growth.official.level'),1);
r("begin('final');if(battle.growth&&Object.keys(battle.growth).length)throw Error('growth carried to next battle')");
r("start('admin');choosePrep('policy');if(battle.maxEnemy!==30||battle.hp!==30)throw Error('HP30');battle.allies=[{id:'official',disabledUntil:0}];battle.growth={official:{progress:2,level:1}};battle.nextBlock=0;battle.plan=[];end();if(battle.block!==5)throw Error('grown start block');battle.allies[0].disabledUntil=battle.turn+1;battle.plan=[];end();if(battle.block!==0)throw Error('disabled start block');battle.enemyPile=Array.from({length:8},()=>makeEnemyCard('parliament',false,0));battle.deferred=[];battle.enemyHand=[];planTurn();if(battle.plan.find(p=>p.effects.some(e=>e.op==='bounce')).target!=='official')throw Error('bounce target');render();if(!document.getElementById('app').innerHTML.includes('issuebadge'))throw Error('issue label');if(!cardHTML(C.answer).includes('コスト 1'))throw Error('visible cost');battle.plan=[makeEnemyCard('finance')];if(can('whip'))throw Error('no-target whip enabled')");
for(let [type,affs] of Object.entries({admin:['admin','politics'],regional:['community','press'],noir:['noir','politics'],economic:['business','admin']})){r(`start('${type}')`);assert(r(`state.deck.every(id=>${JSON.stringify(affs)}.includes(C[id].aff))`));}
for(let phase of ['intro','case','prepared','reward','epilogue','defeat','deck']){r(`state.phase='${phase}';state.reward=[];render()`);for(let m of els.app.innerHTML.matchAll(/onclick="([^"]*)"/g))new Function(m[1]);}r("state.phase='case';choosePrep('policy')");for(let m of els.app.innerHTML.matchAll(/onclick="([^"]*)"/g))new Function(m[1]);
console.log('PASS: deck limits, targeted undo, delayed action budget, issue replacement, scandal/undo, person return, investment, victory confirm, save reload, UI handler syntax.');
