// Equal search effort and owned-copy budgets; holdout never used for deck selection.
const fs=require('fs'),assert=require('assert'),crypto=require('crypto');
const loader=fs.readFileSync('tests/hand_rules_v10.cjs','utf8').split('let sims=')[0].replaceAll('prototypes/kasumigaseki_cards_v10.html','prototypes/kasumigaseki_cards_v14.html').replace('(after.hand-before.hand+1)*1.8','(Math.min(after.hand,7)-Math.min(before.hand-1,7))*1.8').replace('score+=(battle.boost-base.boost)*0.9;','score+=(battle.boost-base.boost)*0.9+(battle.nextDraw-base.nextDraw)*0.9;');
const r=new Function('require',loader+';return load;')(require)('native');
r(`function collectionTrial(type,deck,profile,prep,s){start(type);state.deck=deck.slice();state.owned={};for(let id of deck)state.owned[id]=(state.owned[id]||0)+1;state.difficulty=profile==='intro'?'normal':'advanced';state.challenge=profile;seed=s>>>0;choosePrep(prep);let p=fightMeasured('tactical',true),prepWin=!!state.soft;begin('final');let f=fightMeasured('tactical',true);return {win:state.phase==='reward',prepWin,timeouts:+p.timedOut + +f.timedOut,turns:p.turns+f.turns};}`);
const types=['admin','regional','noir','economic'],preps=['policy','media','party'],profiles=['finance','public'];let rng=1234567;function rand(n){rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng%n;}
const train=Number(process.env.TRAIN||20),trials=Number(process.env.TRIALS||200),candidates=Number(process.env.CANDIDATES||12),rows=[],search=[];
function run(type,deck,profile,prep,n,base){let row={type,profile,prep,total:n,wins:0,prepWins:0,timeouts:0,turns:0,outcomes:''};for(let i=0;i<n;i++){let x=r(`collectionTrial(${JSON.stringify(type)},${JSON.stringify(deck)},'${profile}','${prep}',${base+i*7919})`);row.wins+=x.win;row.prepWins+=x.prepWin;row.timeouts+=x.timeouts;row.turns+=x.turns;row.outcomes+=+x.win;}row.rate=100*row.wins/n;return row;}
for(let type of types){let starter=r(`BASEDECKS.${type}.slice()`),affs=[...new Set(starter.map(id=>r(`C['${id}'].aff`)))],pool=r(`Object.values(C).filter(c=>!c.bad&&${JSON.stringify(affs)}.includes(c.aff)).map(c=>c.id)`);
for(let budget of (process.env.BUDGETS||'twoRewards,fullPair').split(',')){let decks=[starter];for(let k=1;k<candidates;k++){let d=starter.slice();for(let j=0;j<(budget==='twoRewards'?6:12);j++){let pos=rand(20),id=pool[rand(pool.length)],next=d.slice();next[pos]=id;if(next.filter(x=>x===id).length>2)continue;let added=next.reduce((n,x,i)=>n+(i===next.indexOf(x)?Math.max(0,next.filter(y=>y===x).length-(starter.includes(x)?2:0)):0),0);if(budget==='twoRewards'&&added>2)continue;d=next;}assert(d.length===20&&d.every(id=>d.filter(x=>x===id).length<=2));decks.push(d);}
let scores=decks.map((d,index)=>({index,wins:profiles.flatMap(p=>preps.map(prep=>run(type,d,p,prep,train,1357911))).reduce((s,x)=>s+x.wins,0)}));scores.sort((a,b)=>b.wins-a.wins||a.index-b.index);let selected=decks[scores[0].index];search.push({type,budget,affs,pool,trainingScores:scores,selectedIndex:scores[0].index,deck:selected});
for(let profile of ['intro',...profiles])for(let prep of preps){let row=run(type,selected,profile,prep,trials,975310);row.budget=budget;rows.push(row);console.log(type,budget,profile,prep,row.rate);}}
}
let report={version:'v14',sourceSha256:crypto.createHash('sha256').update(fs.readFileSync('prototypes/kasumigaseki_cards_v14.html')).digest('hex'),train,trials,candidates,trainingSeed:1357911,holdoutSeed:975310,method:'Tactical bot; equal randomized candidate search per pair, best average across finance/public and all preparations on training seeds only. TwoRewards: initial owned copies (2 each starter ID) plus at most 2 chosen extra copies. FullPair: all cards in initial two affiliations, max2. No optimality claim; no cross-affiliation builds, random reward probabilities or human test. Intro is holdout only; prepared and final deck identical. Full preparation+final, paired seeds.',search,rows};fs.writeFileSync(process.env.REPORT_PATH||'reports/collection_v14.json',JSON.stringify(report,null,2));assert(rows.every(x=>x.timeouts===0));
