// Controlled final-battle comparison. Uses only published plans and current cards.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync('prototypes/kasumigaseki_cards_v09.html','utf8').split('<script>')[1].split('</script>')[0];const els={};const ctx=vm.createContext({Math,JSON,Object,Array,console,document:{getElementById:id=>els[id]||={innerHTML:'',showModal(){},close(){}}},localStorage:{getItem:()=>null,setItem(){}},confirm:()=>true});vm.runInContext(src,ctx);
vm.runInContext(`render=()=>{};save=()=>{};
function legalActions(){let out=[];for(let i=0;i<battle.hand.length;i++){let id=battle.hand[i];if(!can(id))continue;let e=C[id].effects.find(e=>['cancel','delay'].includes(e.op));if(e){for(let p of validPlans(e))out.push({i,uid:p.uid});}else out.push({i,uid:null});}return out;}
function observed(){return {hp:battle.hp,enemy:battle.enemyHP,blocked:Math.min(battle.block,forecast()),damage:forecast(),people:battle.allies.length,hand:battle.hand.length,energy:battle.energy,investment:battle.invest,futureBlock:battle.nextBlock,grown:Object.values(battle.growth||{}).reduce((n,g)=>n+g.level,0),progress:Object.values(battle.growth||{}).reduce((n,g)=>n+(g.level?0:g.progress),0)};}
function tacticalAction(){let choices=legalActions();if(!choices.length)return null;let base=copy(battle),baseSeed=seed,baseHistory=copy(history),before=observed(),best=null,bestScore=-Infinity;
for(let a of choices){battle=copy(base);seed=baseSeed;history=copy(baseHistory);pending=null;let card=C[battle.hand[a.i]];commit(a.i,a.uid);let after=observed();let score=(before.enemy-after.enemy)*0.85+(after.blocked-before.blocked)*1.05+(before.damage-after.damage)*0.95+(after.hp-before.hp)*1.1+(after.hand-before.hand+1)*1.8+(after.people-before.people)*(battle.turn<=3?5:2)+(after.investment-before.investment)*3+(after.futureBlock-before.futureBlock)*0.45+(after.grown-before.grown)*3+(after.progress-before.progress)*0.7+(after.energy-before.energy)*0.6;
if(after.enemy===0)score+=1000;if(card.aff==='noir')score-=0.8;if(score>bestScore){bestScore=score;best=a;}}
battle=base;seed=baseSeed;history=baseHistory;pending=null;return best;}
function simpleAction(){let legal=legalActions();return legal.find(a=>C[battle.hand[a.i]].type==='person')||legal[0]||null;}
function runTrial(type,difficulty,support,policy,trial){start(type);state.difficulty=difficulty;state.soft=support==='none'?null:support;seed=(1234567+trial*7919)>>>0;begin('final');let steps=0,growth=false,turns=0;
for(let t=0;t<40&&state.phase==='battle';t++){for(let k=0;k<30&&state.phase==='battle'&&!battle.outcome;k++){let a=policy==='tactical'?tacticalAction():simpleAction();if(!a)break;commit(a.i,a.uid);steps++;growth=growth||Object.values(battle.growth||{}).some(g=>g.level);}
if(state.phase==='battle')end();turns++;}return {win:state.phase==='reward',timeout:state.phase==='battle',hp:battle.hp,turns,steps,growth};}
`,ctx);
// Guard against accidental oracle / mutation in action evaluation.
vm.runInContext(`start('admin');seed=123;begin('final');let beforeT=JSON.stringify({battle,seed,history});tacticalAction();if(JSON.stringify({battle,seed,history})!==beforeT)throw Error('evaluation mutates battle');`,ctx);
const trials=Number(process.env.TRIALS||300),rows=[],wins={};function wilson(k,n){let z=1.96,p=k/n,d=1+z*z/n,c=(p+z*z/(2*n))/d,h=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return [c-h,c+h].map(x=>Math.round(x*1000)/10);}
for(const type of ['admin','regional','noir','economic'])for(const difficulty of ['normal','advanced'])for(const support of ['none','finance','press','parliament'])for(const policy of ['simple','tactical']){let k=0,timeouts=0,turns=0,hp=0,growth=0;const outcomes=[];for(let trial=0;trial<trials;trial++){const x=vm.runInContext(`runTrial('${type}','${difficulty}','${support}','${policy}',${trial})`,ctx);outcomes.push(x.win);k+=x.win;timeouts+=x.timeout;turns+=x.turns;if(x.win)hp+=x.hp;growth+=x.growth;}
const key=[type,difficulty,support,policy].join('/');wins[key]=outcomes;rows.push({type,difficulty,support,policy,wins:k,total:trials,rate:Math.round(k/trials*1000)/10,ci95:wilson(k,trials),timeouts,meanTurns:Math.round(turns/trials*10)/10,meanWinHP:k?Math.round(hp/k*10)/10:null,growthRate:Math.round(growth/trials*1000)/10});console.log(key,k+'/'+trials);}
const paired=[];for(const type of ['admin','regional','noir','economic'])for(const difficulty of ['normal','advanced'])for(const policy of ['simple','tactical'])for(const support of ['finance','press','parliament']){let a=wins[[type,difficulty,'none',policy].join('/')],b=wins[[type,difficulty,support,policy].join('/')],gained=0,lost=0;for(let i=0;i<trials;i++){gained+=!a[i]&&b[i];lost+=a[i]&&!b[i];}paired.push({type,difficulty,policy,support,gained,lost,deltaPoints:Math.round((gained-lost)/trials*1000)/10});}
fs.writeFileSync('reports/compare_v09.json',JSON.stringify({sourceSha256:require('crypto').createHash('sha256').update(fs.readFileSync('prototypes/kasumigaseki_cards_v09.html')).digest('hex'),trials,method:'Controlled final only, forced preparation success, seeded; no collection or prep battle; heuristic sees published current plans; not human win rates.',rows,paired},null,2));assert(rows.every(x=>x.timeouts===0),'timeouts');
