const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
// Reuse precisely the same retained-hand engine and observed-information bots.
const loader=fs.readFileSync('tests/hand_rules_v10.cjs','utf8').split('let sims=')[0];const load=new Function('require',loader+';return load;')(require),r=load('retainBoth1');
const cores={admin:['official','leader','answer','answer','procedure','procedure','debate','debate','lobby','lobby','protect','protect','delay','delay','whip','whip'],regional:['reporter','organizer','voice','voice','network','network','petition','petition','return','return','report','report','counter','counter','brief','brief'],noir:['broker','leader','force','force','deal','deal','silence','silence','favor','favor','lobby','lobby','protect','protect','debate','debate'],economic:['economist','official','invest','invest','efficiency','efficiency','reserve','reserve','fund','fund','answer','answer','procedure','procedure','delay','delay']};
const replacements={admin:{draw:['brief','brief','investigate','investigate'],efficient:['network','network','voice','voice']},regional:{draw:['investigate','investigate','clean','clean'],efficient:['answer','answer','protect','protect']},noir:{draw:['brief','brief','investigate','investigate'],efficient:['answer','answer','procedure','procedure']},economic:{draw:['brief','brief','investigate','investigate'],efficient:['debate','debate','protect','protect']}};
const decks={};for(let type of Object.keys(cores))for(let variant of ['efficient','draw']){let deck=[...cores[type],...replacements[type][variant]];assert.equal(deck.length,20);assert(deck.every(id=>deck.filter(x=>x===id).length<=2));decks[type+'/'+variant]=deck;}
r(`const experimentalDecks=${JSON.stringify(decks)};
function deckTrial(type,variant,difficulty,prep,policy,trial){start(type);state.deck=[...experimentalDecks[type+'/'+variant]];for(let id of state.deck)state.owned[id]=2;state.difficulty=difficulty;seed=(789123+trial*7919)>>>0;choosePrep(prep);let pm=fightMeasured(policy,true),prepWin=!!state.soft;begin('final');let fm=fightMeasured(policy,true);return {prepWin,win:state.phase==='reward',prep:pm,final:fm};}
`);
const trials=Number(process.env.TRIALS||100),rows=[];for(let type of Object.keys(cores))for(let variant of ['efficient','draw'])for(let difficulty of ['normal','advanced'])for(let prep of ['policy','media','party'])for(let policy of ['simple','tactical']){let row={type,variant,difficulty,prep,policy,total:trials,wins:0,prepWins:0,turns:0,startHands:0,emptyEnds:0,blockedEnds:0,unusedEnergy:0,capDiscards:0,timeouts:0};for(let i=0;i<trials;i++){let x=r(`deckTrial('${type}','${variant}','${difficulty}','${prep}','${policy}',${i})`);row.wins+=x.win;row.prepWins+=x.prepWin;for(let m of [x.prep,x.final]){for(let k of ['turns','startHands','emptyEnds','blockedEnds','unusedEnergy','capDiscards'])row[k]+=m[k];row.timeouts+=m.timedOut;}}row.rate=Math.round(row.wins/trials*1000)/10;row.meanUnusedEnergy=Math.round(row.unusedEnergy/row.turns*100)/100;row.blockedEndRate=Math.round(row.blockedEnds/row.turns*1000)/10;row.meanStartHand=Math.round(row.startHands/row.turns*100)/100;rows.push(row);console.log([type,variant,difficulty,prep,policy].join('/'),row.rate);}
const source=fs.readFileSync('prototypes/kasumigaseki_cards_v10.html','utf8');fs.writeFileSync('reports/deck_draw_tradeoff.json',JSON.stringify({trials,sourceSha256:crypto.createHash('sha256').update(source).digest('hex'),rule:'Both retain initial5 and draw1. Player cap7, heuristic overflow discard. Additional draw effects unchanged. Same shared16 cards, four deck slots swapped. Existing collectible cards, not starter ownership constraints.',decks,rows},null,2));assert(rows.every(x=>x.timeouts===0));
