const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');const html=fs.readFileSync('prototypes/kasumigaseki_cards_v10.html','utf8'),base=html.split('<script>')[1].split('</script>')[0];
let bot=fs.readFileSync('tests/compare_v09.cjs','utf8').match(/vm.runInContext\(`([\s\S]*?)`,ctx\);/)[1];
bot=bot.replace('if(after.enemy===0)score+=1000;', 'score+=(battle.boost-base.boost)*0.9;if(after.enemy===0)score+=1000;').replace('return best;}', 'return bestScore>0?best:null;}');
function load(rule){let src=base;if(rule.startsWith('retain')){assert(src.includes('draw(5+battle.invest+battle.nextDraw)'));src=src.replace('draw(5+battle.invest+battle.nextDraw)', 'draw((battle.turn===1?5:'+ (rule==='retain2'?2:1) +')+battle.invest+battle.nextDraw)').replace('battle.discard.push(...battle.hand);battle.hand=[];turn();','turn();');}if(rule==='retainBoth1'){src=src.replace('battle.enemyHand=[];for(let i=0;i<5;i++)','battle.enemyHand=battle.enemyHand||[];for(let i=0;i<(battle.turn===1?5:1);i++)').replace('battle.enemyDiscard.push(...battle.enemyHand);battle.enemyHand=[];',"for(let p of battle.plan)if(!p.delayed){let i=battle.enemyHand.findIndex(c=>c.id===p.id);if(i>=0)battle.enemyDiscard.push(battle.enemyHand.splice(i,1)[0]);}");} let els={};let ctx=vm.createContext({Math,JSON,Object,Array,console,document:{getElementById:id=>els[id]||={innerHTML:'',showModal(){},close(){}}},localStorage:{getItem:()=>null,setItem(){}},confirm:()=>true});vm.runInContext(src,ctx);vm.runInContext(bot,ctx);vm.runInContext(`
let metrics;
function capHand(){while(battle.hand.length>7){let ranked=battle.hand.map((id,i)=>({i,value:C[id].bad?-100:C[id].type==='person'&&battle.allies.some(a=>a.id===id)?-20:C[id].type==='person'?3:C[id].type==='attack'?5:C[id].type==='defense'?4:C[id].effects.some(e=>e.op==='draw')?6:2})).sort((a,b)=>a.value-b.value);battle.discard.push(battle.hand.splice(ranked[0].i,1)[0]);metrics.capDiscards++;}}
function fightMeasured(policy,retain){let m={turns:0,startHands:0,emptyEnds:0,blockedEnds:0,unusedEnergy:0,capDiscards:0,timedOut:false};metrics=m;
for(let t=0;t<40&&state.phase==='battle';t++){if(retain)capHand();m.turns++;m.startHands+=battle.hand.length;
for(let k=0;k<30&&state.phase==='battle'&&!battle.outcome;k++){let a=policy==='tactical'?tacticalAction():simpleAction();if(!a)break;commit(a.i,a.uid);if(retain)capHand();}
if(!battle.outcome){m.unusedEnergy+=battle.energy;m.emptyEnds+=battle.hand.length===0;m.blockedEnds+=battle.energy>0&&legalActions().length===0;}if(retain)capHand();end();}
m.timedOut=state.phase==='battle';return m;}
function campaign(type,difficulty,prep,policy,retain,trial){start(type);state.difficulty=difficulty;seed=(456789+trial*7919)>>>0;choosePrep(prep);let pm=fightMeasured(policy,retain),prepWin=!!state.soft;begin('final');let fm=fightMeasured(policy,retain);return {prepWin,win:state.phase==='reward',prep:pm,final:fm};}
`,ctx);return s=>vm.runInContext(s,ctx);}
let sims={discard5:load('discard5'),retain1:load('retain1'),retain2:load('retain2'),retainBoth1:load('retainBoth1')};if(process.env.RULES)for(let k of Object.keys(sims))if(!process.env.RULES.split(',').includes(k))delete sims[k];let r=sims.retain1||load('retain1');r("start('admin');choosePrep('policy');metrics={capDiscards:0};battle.hand=['procedure'];battle.pile=['answer','lobby'];battle.plan=[];end();if(!battle.hand.includes('procedure')||battle.hand.length!==2)throw Error('retain/draw1');battle.hand=Array(9).fill('procedure');capHand();if(battle.hand.length!==7)throw Error('cap');");
let rb=load('retainBoth1');rb("start('admin');choosePrep('policy');battle.enemyHand=[{id:'held',cost:2,effects:[{op:'damage',n:1}]}];battle.enemyPile=[{id:'next',cost:1,effects:[{op:'damage',n:1}]},{id:'fresh',cost:1,effects:[{op:'damage',n:1}]}];battle.turn=2;planTurn();if(battle.enemyHand.length!==2)throw Error('enemy draw1');battle.hand=[];battle.hp=30;end();if(battle.enemyHand.some(c=>c.id==='held'))throw Error('played enemy card retained');");
const n=Number(process.env.TRIALS||100),rows=process.env.RULES?JSON.parse(fs.readFileSync('reports/hand_rules_v10.json','utf8')).rows.filter(x=>!Object.keys(sims).includes(x.rule)):[];for(let rule of Object.keys(sims))for(let type of ['admin','regional','noir','economic'])for(let difficulty of ['normal','advanced'])for(let prep of ['policy','media','party'])for(let policy of ['simple','tactical']){let result={rule,type,difficulty,prep,policy,total:n,wins:0,prepWins:0,turns:0,startHands:0,emptyEnds:0,blockedEnds:0,unusedEnergy:0,capDiscards:0,timeouts:0};for(let trial=0;trial<n;trial++){let x=sims[rule](`campaign('${type}','${difficulty}','${prep}','${policy}',${rule!=='discard5'},${trial})`);result.wins+=x.win;result.prepWins+=x.prepWin;for(let m of [x.prep,x.final]){for(let k of ['turns','startHands','emptyEnds','blockedEnds','unusedEnergy','capDiscards'])result[k]+=m[k];result.timeouts+=m.timedOut;}}result.rate=result.wins/n*100;result.meanStartHand=Math.round(result.startHands/result.turns*100)/100;result.emptyEndRate=Math.round(result.emptyEnds/result.turns*1000)/10;result.blockedEndRate=Math.round(result.blockedEnds/result.turns*1000)/10;result.meanUnusedEnergy=Math.round(result.unusedEnergy/result.turns*100)/100;rows.push(result);console.log([rule,type,difficulty,prep,policy].join('/'),result.rate);}
fs.writeFileSync(process.env.REPORT_PATH||'reports/hand_rules_v10.json',JSON.stringify({sourceSha256:crypto.createHash('sha256').update(html).digest('hex'),trials:n,method:'Paired full campaigns; initial hand5, retain and draw1 or draw2; additional draws unchanged; cap7 automatic heuristic discards; cap after draw/action; retainBoth1 also retains enemy hand, draws1, discards committed actions only; no free discard except overflow. Intent-aware policy can end turn to conserve cards, considers attack preparation; not optimal multi-turn play. Main game not modified.',rows},null,2));assert(rows.every(x=>x.timeouts===0),'timeout');
