const fs=require('fs'),assert=require('assert'),crypto=require('crypto'),load=require('./runtime_v18.cjs');
const r=load(),n=Number(process.env.TRIALS||100),base=Number(process.env.SEED_BASE||641852),rows=[];
if(process.env.PILOT_BONUS)r(`const pilotEnemyDeck=enemyDeck;enemyDeck=function(kind){let cards=pilotEnemyDeck(kind);if(kind==='final'&&caseProfile()===CASE_PROFILES.pollution)for(let c of cards)for(let e of c.effects)if(e.op==='damage')e.n+=${Number(process.env.PILOT_BONUS)};return cards;};`);
const bank=JSON.parse(fs.readFileSync('reports/attribute_pairs_v17.json','utf8')).search;
const manual={admin:[['leader','environmentOfficer'],['staffChange','jointStatement']],regional:[['organizer','residentAdvocate'],['routeExplain','testimony']],noir:[['leader','industryBroker'],['staffChange','secretSettlement']],economic:[['economist','transitionAdvisor'],['projectReview','equipmentRenewal']]};
r(`function testCase(deck,profile,prep,policy,s){start('admin');state.deck=deck.slice();state.owned={};for(let id of deck)state.owned[id]=(state.owned[id]||0)+1;state.difficulty=profile==='intro'?'normal':'advanced';state.challenge=profile;state.chapterTwoUnlocked=profile==='pollution';seed=s>>>0;choosePrep(prep);let pm=fightMeasured(policy,true);let prepWin=!!state.soft;begin('final');let fm=fightMeasured(policy,true);return {win:state.phase==='reward',prepWin,timeouts:+pm.timedOut + +fm.timedOut};}`);
const decks=[];for(let type of ['admin','regional','noir','economic']){let starter=r(`BASEDECKS.${type}.slice()`),edited=starter.slice();for(let [from,to] of manual[type]){let i=edited.indexOf(from);assert(i>=0);edited[i]=to;}decks.push({name:type+' starter',deck:starter},{name:type+' new-card example',deck:edited});}
for(let pair of ['admin+noir','admin+community','admin+press','press+noir'])decks.push({name:pair+' collected',deck:bank.find(x=>x.affs.join('+')===pair).deck});
for(let entry of decks.filter(d=>!process.env.NAMES||process.env.NAMES.split(',').includes(d.name)))for(let profile of (process.env.PROFILES||'pollution').split(','))for(let prep of ['policy','media','party'])for(let policy of (process.env.POLICIES||'tactical').split(',')){let row={name:entry.name,profile,prep,policy,total:n,wins:0,prepWins:0,timeouts:0};for(let i=0;i<n;i++){let x=r(`testCase(${JSON.stringify(entry.deck)},'${profile}','${prep}','${policy}',${base+i*7919})`);row.wins+=x.win;row.prepWins+=x.prepWin;row.timeouts+=x.timeouts;}row.rate=100*row.wins/n;rows.push(row);console.log(row.name,profile,prep,policy,row.rate.toFixed(1));}
const source=fs.readFileSync('prototypes/kasumigaseki_cards_v18.html');fs.writeFileSync(process.env.REPORT_PATH||'reports/pollution_v18.json',JSON.stringify({sourceSha256:crypto.createHash('sha256').update(source).digest('hex'),n,base,pilotBonus:Number(process.env.PILOT_BONUS||0),nameFilter:process.env.NAMES||null,method:'Fixed starters, two predetermined swaps each (new-card examples assume acquired cards, not earned reward), and four previously selected v17 full-collection recipes. Full preparation+final, 3 preparations, fixed policies, paired seeds. No deck selection on these results. No human/browser test.',decks,rows},null,2));assert(rows.every(x=>!x.timeouts));
